[tools] Create sc-component-manager base structure
ostis-ai/sc-component-manager pull request #1
Opened 2022-08-09 13:48 UTC by MksmOrlov

2022-10-20 20:04 UTC, NikitaZotov requested changes

2022-10-20 20:04 UTC, NikitaZotov commented on src/manager/commands/command_init/repos_parser/repos_parser.cpp
> +  if (reposFile.is_open())
What will be if file doesn't exist?

2022-10-20 20:04 UTC, NikitaZotov commented on src/manager/commands/command_init/repos_downloader/repos_downloader_handler.hpp
> +    pathStream << specificationDirName << '/' << SpecificationConstants::SPECIFICATION_FILENAME;
Add var for string literal

2022-10-20 20:04 UTC, NikitaZotov commented on src/main.cpp
> +sc_int main(sc_int argc, sc_char * argv[])
I think that in some case sc-server will be needed. Now sc-component-manager has console interface, but it will be made as component of platform interface. When sc-server will be used anyway

2022-10-20 20:04 UTC, NikitaZotov commented on README.md
> +- components init - downloading specifications from repos.txt sources to _specifications_ folder (automatically created if is not exists)
Do you want make documentation in scn-tex format and use ostis-library to describe sc-component-manager?

2022-10-20 21:35 UTC, MksmOrlov commented on README.md
> +Example of components specification (specification.scs file)
Я собираюсь базу знаний добавить в будущем тут. Там и будет спецификация, в стандарте сейчас есть этот материал. Да и пример этот неактуальных, хотя и функционал не затрагивает эту часть на данном этапе.
Да и в принципе документация в формате стандарта тоже есть, здесь чисто ридмишка для быстрого старта, потом поменяется

2022-10-20 22:06 UTC, MksmOrlov commented on src/manager/commands/sc_component_manager_command_handler.hpp
> +      std::cout << "ScComponentManagerCommandHandler: execute " + it->first + " command\n";
Потому что не работает, не удалось подключить. Мы с тобой решили сделать это позже

2022-10-20 22:09 UTC, MksmOrlov commented on tests/units/test_repos_parser.cpp
> +  std::vector<std::string> repositories = {"https://github.com/MksmOrlov/components-repo-example/repos.txt"};
И что делать?

2022-10-20 22:11 UTC, MksmOrlov commented on tests/units/test_repos_parser.cpp
> +#include "sc_component_manager_test.hpp"
Сделаю после

2022-10-20 22:12 UTC, MksmOrlov commented on src/manager/commands/command_init/repos_parser/repos_parser.cpp
> +  if (reposFile.is_open())
Ничего. Список доступных компонентов пустой

2022-10-20 22:14 UTC, MksmOrlov commented on src/main.cpp
> +sc_int main(sc_int argc, sc_char * argv[])
Да

2022-10-20 22:15 UTC, MksmOrlov commented on README.md
> +- components init - downloading specifications from repos.txt sources to _specifications_ folder (automatically created if is not exists)
Да, она уже есть в стандарте/документе. Ридмишка это для быстрого старта

2022-11-07 12:37 UTC, MksmOrlov commented on tests/units/sc_component_manager_test.hpp
> +#include "src/manager/commands/command_init/repos_parser/repos_parser.hpp"
В другом ПРе будет рефактор

2022-11-07 12:38 UTC, MksmOrlov commented on src/manager/sc_component_manager.cpp
> +#include "src/manager/commands/sc_component_manager_command.hpp"
Это тоже в другом ПРе

2022-11-08 09:38 UTC, NikitaZotov requested changes

2022-11-08 09:38 UTC, NikitaZotov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +        if (currentCommandToken.at(0) == '\"')
What is 0?

2022-11-08 09:38 UTC, NikitaZotov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +          currentCommandToken = currentCommandToken.substr(1, currentCommandToken.size() - 1);
What is 1?

2022-11-08 09:38 UTC, NikitaZotov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +      return currentCommandToken.substr(1);
What do this constants mean?

2022-11-08 09:38 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +        if (currentCommandToken.at(0) == '\"')
![image](https://user-images.githubusercontent.com/36566977/200529533-8262fdb4-761f-494b-a173-a11217378f8e.png)

2022-11-08 09:38 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +          currentCommandToken = currentCommandToken.substr(1, currentCommandToken.size() - 1);
![image](https://user-images.githubusercontent.com/36566977/200529630-df40219e-1628-496d-bb0c-9fb15238fd30.png)

2022-11-08 09:39 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +      return currentCommandToken.substr(1);
dashes before parameter flag  (--param or -p)

2022-11-08 09:40 UTC, NikitaZotov approved these changes

2022-11-08 11:26 UTC, merged