[install] Check if component is loaded
ostis-ai/sc-component-manager pull request #106
Opened 2024-04-29 04:50 UTC by MakarenkoAI

2024-04-29 10:13 UTC, MksmOrlov requested changes
Change in test scs sc-web specification class ui component.
And I've got an error
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/94e66db4-45fa-4af2-ab03-f77358df95a2)

2024-05-15 09:17 UTC, MksmOrlov requested changes
Update documentation please with pictures of new install agent constructions

2024-05-15 09:17 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +}  // namespace common_utils
Add newline please

2024-05-15 09:17 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
Remove this method and use IteratorUtils::GetAnyByOutRelation instead
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/2875eb53-f44c-4e37-b32d-4b877fa55d85)

2024-05-15 09:17 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
Use  IteratorUtils::GetAnyByOutRelation
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/d7c788a0-7ada-4f8f-b18d-15e92e23ffaf)

2024-05-15 09:17 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +                                                << context->HelperGetSystemIdtf(reusableComponent));
Use auto formatter after approve

2024-05-15 09:17 UTC, MksmOrlov commented on src/manager/console-interface/command_parser/sc_component_manager_command_parser.hpp
> +    //    SC_LOG_WARNING(cutCommand);
remove comments in this file

2024-05-18 20:04 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      {"set", scAgentsCommon::CoreKeynodes::rrel_1},
rrel_set?

2024-05-18 20:04 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      };
rrel_identificator instead of components?

2024-05-20 08:23 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      std::vector<ScAddr> idtfWithComponentsAddrs;
rename
```suggestion
      std::vector<ScAddr> componentsAddrs;
```

2024-05-21 10:07 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      };
no

2024-05-21 10:08 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      {"set", scAgentsCommon::CoreKeynodes::rrel_1},
rrel_sets

2024-05-21 17:05 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/06888f37-335b-407e-852a-2f2a39284020)

2024-05-23 16:23 UTC, MksmOrlov requested changes

2024-05-23 16:23 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      }
why do you need this construction?

2024-05-23 16:23 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      }
Refactor the method very please

2024-05-28 15:09 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
>  bool CommonUtils::TransformToScStruct(
rename

2024-06-04 08:54 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +std::set<ScAddr, ScAddrLessFunc> CommonUtils::GetComponentsToInstall(
```suggestion
std::unordered_set<ScAddr, ScAddrLessFunc> CommonUtils::GetComponentsToInstall(
```
Unordered set is better because we don't need to sort elements while adding to the set. It is more efficient. Check everywhere

2024-06-04 08:54 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +ScAddrVector CommonUtils::GetInstallationComponents(
Do not use std::set where you can use std::unordered_set. Unordered set is better because we don't need to sort elements while adding to the set. It is more efficient. Check everywhere

2024-06-04 08:57 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  ScAddr const & parameterNode = utils::IteratorUtils::getAnyByOutRelation(&context, actionAddr, relationAddr);
You still find `parameterNode` inside the method.

2024-06-05 14:51 UTC, MksmOrlov requested changes
Testing is OK.
And replace ScAddrVector to ScAddrUnorderedSet in Execute methods.

2024-06-05 14:51 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.hpp
> +  typedef std::unordered_set<ScAddr, ScAddrHashFunc<sc_uint32>> unorderedSetScAddr;
```suggestion
  using std::unordered_set<ScAddr, ScAddrHashFunc<sc_uint32>> ScAddrUnorderedSet;
```

2024-06-06 08:54 UTC, MksmOrlov requested changes

2024-06-06 08:54 UTC, MksmOrlov commented on src/manager/agents/common-module/commands/sc_component_manager_command.hpp
> +  virtual std::unordered_set<ScAddr, ScAddrHashFunc<sc_uint32>> Execute(
Use ScAddrUnorderedSet

2024-06-06 08:54 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +CommonUtils::ScAddrUnorderedSet CommonUtils::GetComponentsToInstall(
```suggestion
ScAddrUnorderedSet CommonUtils::GetComponentsToInstall(
```
You are already in common utils. Remove everywhere. Use using namespace if it is required

2024-06-06 08:54 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::CommonUtils::ScAddrUnorderedSet ScComponentManagerCommandSearch::Execute(
```suggestion
ScAddrUnorderedSet ScComponentManagerCommandSearch::Execute(
```
Everywhere

2024-06-06 13:32 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +  common_utils::ScAddrUnorderedSet availableComponents;
without common_utils::

2024-06-06 13:32 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +    common_utils::ScAddrUnorderedSet const & componentsToInstall)
without common_utils::

2024-06-06 13:32 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandInstall::GetAvailableComponents(
without common_utils::

2024-06-06 13:34 UTC, MksmOrlov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandInit::Execute(
without common_utils::

2024-06-06 13:34 UTC, MksmOrlov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +  common_utils::ScAddrUnorderedSet components;
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandInstall::Execute(
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +  common_utils::ScAddrUnorderedSet componentsToInstall =
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandSearch::Execute(
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  std::map<std::string, common_utils::ScAddrUnorderedSet> linksValues;
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +    common_utils::ScAddrUnorderedSet explanationLinks = SearchComponentsByRelationLink(
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  common_utils::ScAddrUnorderedSet componentsSpecifications =
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandSearch::SearchComponentsByRelationLink(
without common_utils::

2024-06-06 13:35 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandSearch::SearchComponentsSpecifications(
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +    std::map<std::string, common_utils::ScAddrUnorderedSet> const & linksValues)
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  common_utils::ScAddrUnorderedSet result;
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandSearch::SearchComponentsSpecificationsWithoutLinks(
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  common_utils::ScAddrUnorderedSet result;
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +common_utils::ScAddrUnorderedSet ScComponentManagerCommandSearch::SearchComponentsSpecificationsWithLinks(
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +    std::map<std::string, common_utils::ScAddrUnorderedSet> const & linksValues)
without common_utils::

2024-06-06 13:36 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  common_utils::ScAddrUnorderedSet result;
without common_utils::

2024-06-06 13:53 UTC, MksmOrlov approved these changes

2024-06-07 05:11 UTC, PetrochukKsenija approved these changes

2024-06-10 12:16 UTC, merged