feat: add new search flags
ostis-ai/sc-component-manager pull request #109
Opened 2024-05-23 08:26 UTC by PetrochukKsenija

Для проверки:
**Поиск по идентификатору:** cs --id "cat"
**Поиск по цели:** cs --purpose "Cat"  
**Поиск по примечанию:** cs --note "Cat"
**Поиск по ключевому элементу:** cs --key concept_animal

Во всех случаях должно найти следующий компонент:
ScComponentManager: cat_reusable_component_specification concept_cat

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-05-23 09:44 UTC, MakarenkoAI requested changes

2024-05-23 09:44 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      }
easier not to repeat equal code
```suggestion
      else if (parameter.first == CommandsConstantsFlags::NOTE || ...) 
      {
        parameterValueAddr = context.CreateNode(ScType::LinkConst);
        context.SetLinkContent(parameterValueAddr, parameterValue);
      }
```
or create the list of flagsAddrs and check, if parameter.first is in this list

2024-05-23 09:44 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +      GetParameterNodeUnderRelation(context, actionAddr, keynodes::ScComponentManagerKeynodes::rrel_note);
I removed this method, use getAnybyOutrelation

2024-05-23 09:44 UTC, MakarenkoAI commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +// void ScComponentManagerCommandSearch::SearchComponentsByKeyElement(
Remove, please

2024-05-23 09:45 UTC, MakarenkoAI reviewed
and update docs, please

2024-05-23 09:51 UTC, MakarenkoAI commented on kb/relations.scs
> +  [purpose'] (* <- lang_en;; *);;
```suggestion
=> nrel_main_idtf:
    [цель'] (* <- lang_ru;; *);
    [purpose'] (* <- lang_en;; *);;
```

2024-05-30 09:14 UTC, MksmOrlov requested changes

2024-05-30 09:14 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  ScAddr const & notesSetAddr =
Method `GetCommandParameter` should be removed

2024-05-30 09:14 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> -      scAgentsCommon::CoreKeynodes::rrel_key_sc_element);
why do you remove it?

2024-05-30 09:14 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +std::vector<std::string> ScComponentManagerCommandSearch::SearchComponents(
whyy? We need std::unordered_set in all methods to prevent duplicates. Also it is better to iterate and get elements

2024-05-30 09:14 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +    result.push_back(context->HelperGetSystemIdtf(reusableComponent));
we should work with ScAddrs, not with strings here

2024-06-17 10:15 UTC, MksmOrlov commented
> and update docs, please use clang-format also Works good, but maybe it's better to find strings by transferring in lower(upper) case **cs --purpose "Cat"** and **cs --purpose "cat"** to see the same result
Case sensitivitysearch  is a task of sc-machine

2024-08-12 17:18 UTC, MksmOrlov commented
Merged in https://github.com/ostis-ai/sc-component-manager/pull/112

2024-08-12 17:18 UTC, closed without merging