[feat] Add new search flags
ostis-ai/sc-component-manager pull request #112
Opened 2024-06-17 08:00 UTC by PetrochukKsenija

Для проверки:
Поиск по идентификатору: cs --main-id "cat" или cs --main-id "кот"
Поиск по цели: cs --purpose "Cat"
Поиск по примечанию: cs --note "Cat"
Поиск по ключевому элементу: cs --key concept_animal

Во всех случаях должно найти следующий компонент:
ScComponentManager: specification is cat_reusable_component_specification, component is concept_cat

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-06-17 09:05 UTC, MakarenkoAI requested changes

2024-06-17 09:05 UTC, MakarenkoAI commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  ScAddr const & notesSetAddr = utils::IteratorUtils::getAnyByOutRelation(
You can all repeated code move to one cycle

2024-06-17 09:05 UTC, MakarenkoAI commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +  if (commandParameters.find(NOTE) != commandParameters.cend()
And there also can me cycle **for** instead of **if**

2024-06-17 09:11 UTC, MakarenkoAI commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
![image](https://github.com/ostis-ai/sc-component-manager/assets/90891293/9e1c50e4-e293-4ff8-82d3-364684f790fb)

2024-06-17 13:07 UTC, MksmOrlov requested changes

2024-06-24 09:28 UTC, PetrochukKsenija commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  ScAddr const & notesSetAddr = utils::IteratorUtils::getAnyByOutRelation(
Pointers (&) are used in this section of the code, so it is problematic to optimize this code normally

2024-06-24 14:34 UTC, MksmOrlov requested changes

2024-06-24 14:34 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +      SC_LOG_INFO(std::get<0>(searchByLine[sequenceNumber]));
remove it please

2024-06-24 14:34 UTC, MksmOrlov commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +   for (int sequenceNumber = 0; sequenceNumber < searchByRelation.size(); sequenceNumber++)
```suggestion
   for (size_t sequenceNumber = 0; sequenceNumber < searchByRelation.size(); sequenceNumber++)
```

2024-06-26 09:13 UTC, MakarenkoAI commented on src/manager/agents/search-module/utils/sc_component_manager_command_search.cpp
> +      ScAddrUnorderedSet links = SearchComponentsByRelationLink(
process exception with **try catch**

2024-06-27 17:47 UTC, MksmOrlov approved these changes

2024-07-05 14:41 UTC, MakarenkoAI approved these changes

2024-07-08 09:18 UTC, merged