Fix/init command
ostis-ai/sc-component-manager pull request #113
Opened 2024-06-17 18:43 UTC by MksmOrlov

- Do not crush and wait init agent if one of specification is broken
- Remove recursive repository logic
- Some refactor, optimisation and log improvements

2024-06-18 08:04 UTC, MakarenkoAI approved these changes

2024-06-18 08:04 UTC, MakarenkoAI commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +ScAddrUnorderedSet ScComponentManagerCommandInit::ProcessRepository(ScMemoryContext * context, ScAddr & repository)
```suggestion
ScAddrUnorderedSet ScComponentManagerCommandInit::ProcessRepository(ScMemoryContext * context, ScAddr & repositoryAddr)
```

2024-06-19 16:03 UTC, NikitaZotov requested changes

2024-06-19 16:03 UTC, NikitaZotov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +    ScAddrUnorderedSet specificationsTemp = ProcessRepository(context, repository);
Could you provide & param for `ProcessRepository` to avoid copying `specificationsTemp` in lines 26 and 27?

2024-06-19 16:03 UTC, NikitaZotov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +    componentSpecification = specificationsIterator->Get(2);
```suggestion
    componentSpecificationAddr = specificationsIterator->Get(2);
```

2024-06-19 16:03 UTC, NikitaZotov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +    component = CommonUtils::GetComponentBySpecification(*context, componentSpecification);
```suggestion
    componentAddr = CommonUtils::GetComponentBySpecification(*context, componentSpecification);
```

2024-06-19 16:18 UTC, MksmOrlov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +ScAddrUnorderedSet ScComponentManagerCommandInit::ProcessRepository(ScMemoryContext * context, ScAddr & repository)
I can't agree with you because we already work in  sc-memory with sc-elements and there is no need to duplicate "Addr" in varname especially if there is no same object with other type

2024-06-19 16:18 UTC, MksmOrlov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +    component = CommonUtils::GetComponentBySpecification(*context, componentSpecification);
I can't agree with you because we already work in  sc-memory with sc-elements and there is no need to duplicate "Addr" in varname especially if there is no same object with other type

2024-06-19 17:21 UTC, NikitaZotov approved these changes

2024-06-19 17:21 UTC, merged