Refactor/remove codegen
ostis-ai/sc-component-manager pull request #117
Opened 2024-09-12 08:48 UTC by kilativ-dotcom

* [X] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-09-12 20:37 UTC, NikitaZotov requested changes

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.cpp
> +  SC_AGENT_LOG_INFO("finished");
```suggestion
```

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.cpp
> +  SC_AGENT_LOG_INFO("started");
```suggestion
```

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.cpp
> +  SC_AGENT_LOG_DEBUG("finished");
```suggestion
```

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.cpp
> +  SC_AGENT_LOG_DEBUG("started");
```suggestion
```

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/search-module/module/agents/sc_component_manager_agent_search.cpp
> +  SC_AGENT_LOG_DEBUG("started");
```suggestion
```

2024-09-12 20:37 UTC, NikitaZotov commented on src/manager/agents/search-module/module/agents/sc_component_manager_agent_search.cpp
> +  return action.FinishSuccessfully();
```suggestion
```

2024-09-19 13:35 UTC, MakarenkoAI requested changes

2024-09-19 13:35 UTC, MakarenkoAI commented on docs/main.synctex.gz
remove it

2024-09-19 13:35 UTC, MakarenkoAI commented on src/manager/agents/common-module/downloader/downloader_git.hpp
> +      SC_LOG_ERROR("Can't download repository. Can't create folder. " << downloadPath);
```suggestion
      SC_AGENT_LOG_ERROR("Can't download repository. Can't create folder. " << downloadPath);
```

2024-09-19 13:35 UTC, MakarenkoAI commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
>            "ScComponentManagerCommandInstall: Validating component \""
```suggestion
          "Validating component \""
```

2024-09-19 13:55 UTC, kilativ-dotcom commented on src/manager/agents/common-module/downloader/downloader_git.hpp
> +      SC_LOG_ERROR("Can't download repository. Can't create folder. " << downloadPath);
эту ерунду можно только в агентах использовать, я могу добавить DownloaderGit к сообщению

2024-10-01 06:21 UTC, kilativ-dotcom commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
>            "ScComponentManagerCommandInstall: Validating component \""
probably same issue as your previous comment

2024-10-03 10:46 UTC, NikitaZotov requested changes

2024-10-07 07:10 UTC, NikitaZotov approved these changes

2024-10-24 09:32 UTC, MakarenkoAI approved these changes

2024-10-24 09:39 UTC, merged