[doc] Update readme
ostis-ai/sc-component-manager pull request #14
Opened 2023-02-16 14:10 UTC by SHtress

2023-02-20 08:27 UTC, NikitaZotov approved these changes

2023-02-21 06:45 UTC, MksmOrlov requested changes

2023-02-21 06:45 UTC, MksmOrlov commented on README.md
> +- Install ostis-web-platform with sc-machine branch **feature/component_manager**
Write about where to change branch (prepare.sh line 47)

2023-02-21 06:45 UTC, MksmOrlov commented on README.md
> +## Usage
Please, write how to run sc-component-manager

2023-02-21 06:45 UTC, MksmOrlov commented on README.md
> +- components search  [--author \<author\>][--class \<class\>][--explanation \<"explanation"\>] - searching component specification in knowledge base. You can search components by author, class or exp
```suggestion
- components search  [--author \<author\>][--class \<class\>][--explanation \<"explanation"\>] - searching component specification in knowledge base. You can search components by author, class or explanation substring.
```

2023-02-21 06:45 UTC, MksmOrlov commented on src/main.cpp
> +#include "src/manager/sc-component-manager-factory/sc_component_manager_factory.hpp"
Create separate commit or PR for this changes

2023-02-21 07:58 UTC, SHtress commented on README.md
> +- Install ostis-web-platform with sc-machine branch **feature/component_manager**
I will make one

2023-02-21 07:58 UTC, SHtress commented on README.md
> +- Install ostis-web-platform with sc-machine branch **feature/component_manager**
No need if i create branch in ostis-web-platform

2023-02-21 07:59 UTC, SHtress commented on README.md
> +## Usage
Okay, maybe add script to ostis-web-platform branch

2023-02-21 14:51 UTC, SHtress commented on src/main.cpp
> +#include "src/manager/sc-component-manager-factory/sc_component_manager_factory.hpp"
Separate commit

2023-02-22 15:39 UTC, MksmOrlov approved these changes
Make one commit and merge

2023-02-22 15:40 UTC, KovalM approved these changes

2023-02-24 18:43 UTC, merged