[init][install] Recursive specification download
ostis-ai/sc-component-manager pull request #15
Opened 2023-02-21 12:01 UTC by SHtress

2023-02-21 12:28 UTC, NikitaZotov requested changes

2023-02-21 12:28 UTC, NikitaZotov commented on src/manager/commands/command_init/repos_downloader/repos_downloader_handler.cpp
> +  pathStream << specificationDirName << DIRECTORY_DELIMITER << SpecificationConstants::REPOS_FILENAME;
It may call error if path is not valid. Handle error situations, please. Use try/catch statements

2023-02-21 12:28 UTC, NikitaZotov commented on src/manager/commands/command_init/sc_component_manager_command_init.hpp
> +    std::set<ScAddr, ScAddLessFunc> processedRepositories;
May be to add alias for this complex type?

2023-02-21 12:28 UTC, NikitaZotov commented on src/manager/commands/command_init/sc_component_manager_command_init.hpp
> +    ScIterator3Ptr iterator3 = context->Iterator3(
```suggestion
    ScIterator3Ptr const iterator3 = context->Iterator3(
```

2023-02-21 12:28 UTC, NikitaZotov commented on src/manager/commands/command_init/sc_component_manager_command_init.hpp
>      //    TODO(MksmOrlov): implement recursion to handle repositories
Remove TODO

2023-02-23 08:48 UTC, SHtress commented on src/manager/commands/command_init/sc_component_manager_command_init.hpp
> +    std::set<ScAddr, ScAddLessFunc> processedRepositories;
Where?

2023-04-06 19:40 UTC, SHtress commented
Fixed in #30

2023-04-06 19:40 UTC, closed without merging