[refactor][utils] Create utils for component manager
ostis-ai/sc-component-manager pull request #23
Opened 2023-03-02 13:26 UTC by SHtress

Move frequently used functions to utils: GetComponentAddress, GetComponentDependencies, GetComponentInstallationMethod

2023-03-02 18:19 UTC, MksmOrlov requested changes
I suggest to name directory as "utils", not "component_utils"

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.cpp
> +  ScIterator5Ptr const componentDependenciesIterator = context->Iterator5(
```suggestion
  ScIterator5Ptr const & componentDependenciesIterator = context->Iterator5(
```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.cpp
> +  }
Move declaration from cycle
```suggestion
  ScAddr componentDependenciesSet;
  ScAddrVector componentCurrentDependencies;
  while (componentDependenciesIterator->Next())
  {
    componentDependenciesSet = componentDependenciesIterator->Get(2);
    componentCurrentDependencies =
        utils::IteratorUtils::getAllWithType(context, componentDependenciesSet, ScType::NodeConst);
    componentDependencies.insert(
        componentDependencies.cend(), componentCurrentDependencies.cbegin(), componentCurrentDependencies.cend());
  }
```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.cpp
> +    componentInstallationMethod = componentDependenciesIterator->Get(2);
```suggestion
  if (componentDependenciesIterator->Next())
  {
    componentInstallationMethod = componentDependenciesIterator->Get(2);
  }
```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.cpp
> +}  // namespace utils
```suggestion
}

}  // namespace utils

```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.hpp
> +class ComponentUtils
```suggestion
{

class ComponentUtils
```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.hpp
> +}  // namespace utils
```suggestion
};

}  // namespace utils

```

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.hpp
> +class ComponentUtils
I'd like to name it like "SearchUtils". Or smth like that to identify that there are "GetSmth" methods

2023-03-02 18:19 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.hpp
> +namespace utils
I'd like to name it like "componentUtils"

2023-03-06 17:31 UTC, SHtress commented on src/manager/commands/command_install/sc_component_manager_command_install.cpp
> +#include "src/manager/component_utils/sc_component_utils.hpp"
For now we need loader for installation after download, but in further pr after installation method update i remove scs_loader

2023-03-06 17:33 UTC, SHtress commented on src/manager/component_utils/sc_component_utils.cpp
> +std::string ComponentUtils::GetComponentAddress(ScMemoryContext * context, ScAddr const & componentAddr)
Update to just take content in install method

2023-03-06 17:44 UTC, SHtress commented on src/manager/component_utils/sc_component_utils.cpp
> +    componentAddress = utils::CommonUtils::getLinkContent(context, componentAddressAddr);
Context method returns ScStream and method from utils just validates it and converts to string

2023-03-06 18:22 UTC, MksmOrlov requested changes

2023-03-06 18:22 UTC, MksmOrlov commented on src/manager/commands/command_install/sc_component_manager_command_install.cpp
> +      componentDirName += componentAddressContent.substr(componentDirNameIndex);
use stringstream. Do not concatenate strings

2023-03-06 18:22 UTC, MksmOrlov commented on src/manager/utils/sc_component_utils.cpp
> +
empty lines. add licence header

2023-03-06 18:22 UTC, MksmOrlov commented on src/manager/utils/sc_component_utils.hpp
> +#pragma once
add licence header

2023-03-06 18:27 UTC, MksmOrlov requested changes

2023-03-06 18:27 UTC, MksmOrlov commented on src/manager/commands/command_install/sc_component_manager_command_install.cpp
> +  std::string const & componentAddressContent = utils::CommonUtils::getLinkContent(context, componentAddressAddr);
use ScMemoryContext method to get link content

2023-03-06 18:29 UTC, MksmOrlov commented on src/manager/component_utils/sc_component_utils.cpp
> +    componentAddress = utils::CommonUtils::getLinkContent(context, componentAddressAddr);
No, use another method

2023-03-06 18:39 UTC, SHtress commented on src/manager/commands/command_install/sc_component_manager_command_install.cpp
> +      componentDirName += componentAddressContent.substr(componentDirNameIndex);
Should we fix it now cause next pr will update whole download and install methods?

2023-03-06 18:59 UTC, MksmOrlov approved these changes

2023-03-07 11:54 UTC, smousy approved these changes

2023-03-07 12:23 UTC, merged