[init] Update init command and components downloading process
ostis-ai/sc-component-manager pull request #24
Opened 2023-03-11 12:21 UTC by SHtress

2023-03-23 00:24 UTC, smousy requested changes

2023-03-23 00:24 UTC, smousy commented on src/manager/commands/command_init/downloader/downloader_handler.hpp
> +  std::map<ScAddr, Downloader *, ScAddrLessFunc> m_downloaders = {
or rename it everywhere

2023-03-23 00:31 UTC, smousy requested changes

2023-03-23 00:31 UTC, smousy commented on src/manager/commands/command_init/downloader/downloader_handler.cpp
> +  return ScAddr::Empty;
maybe we can add variable and keep only one return?

2023-03-23 00:31 UTC, smousy commented on src/manager/utils/sc_component_utils.cpp
> +  return specificationAddressLinks;
please keep only one return

2023-03-27 06:06 UTC, SHtress commented on src/manager/commands/command_init/downloader/downloader_handler.hpp
> +  std::map<ScAddr, Downloader *, ScAddrLessFunc> m_downloaders = {
Fixed in sc-machine.

2023-03-27 06:32 UTC, SHtress commented on src/manager/utils/sc_component_utils.cpp
> +    SC_LOG_ERROR("No links for repository address found");
Great idea, thanks!

2023-03-27 08:16 UTC, smousy requested changes

2023-03-27 08:16 UTC, smousy commented on src/manager/commands/keynodes/ScComponentManagerKeynodes.hpp
> +  // static ScAddr rrel_address;
if you don't need it, please delete

2023-03-27 08:18 UTC, SHtress commented on src/manager/commands/command_init/downloader/downloader_handler.cpp
> +    nodeAddressLinkAddrs = componentUtils::SearchUtils::GetSpecificationAddress(context, nodeAddr);
Forgot about this, thanks for remind.

2023-03-27 09:22 UTC, smousy approved these changes

2023-03-27 09:35 UTC, merged

2023-03-28 12:07 UTC, SHtress commented on kb/specifications.scs
>  	-> ... (* -> rrel_address: [https://drive.google.com/file/d/1eUxPBd3VKNFSDEgolz11EQdEmBJMFYIk/view?usp=sharing];; *);;
I will add task for specification update. This will include formatting too.

2023-03-28 12:09 UTC, SHtress commented on src/manager/commands/command_init/downloader/downloader_google_drive.hpp
> +    // ScExec exec{{gDriveInstallCommand}};
We discussed this on 28.03. After environment configuration, we probably remove Google Drive support.

2023-03-28 12:10 UTC, SHtress commented on src/manager/commands/command_init/downloader/downloader_handler.cpp
> + * @return Sc-addr of node class if it can be downloaded,
Code style docs will be done in environment configuration task.

2023-03-28 12:11 UTC, SHtress commented on src/manager/commands/command_install/sc_component_manager_command_install.cpp
> +  }
Thanks, i will check it.