[docs] Update README example
ostis-ai/sc-component-manager pull request #36
Opened 2023-04-10 17:54 UTC by SHtress

2023-04-10 18:29 UTC, MksmOrlov requested changes

2023-04-10 18:29 UTC, MksmOrlov commented on README.md
> +## Repository and components
There is no `Repository`, we name it as a `Storage` now

2023-04-10 18:29 UTC, MksmOrlov commented on README.md
>  ```scs
Add SCg example like that
![image](https://user-images.githubusercontent.com/36566977/230963658-9e0604f9-fd05-48e2-ba25-cf45189d5db1.png)

2023-04-10 18:29 UTC, MksmOrlov commented on README.md
>  ```scs
add SCg example

2023-04-10 18:32 UTC, SHtress commented on README.md
> +## Repository and components
Maybe, but until it changed everywhere it stays as Repository. Not for this PR.

2023-04-10 18:35 UTC, SHtress commented on README.md
> +## Repository and components
Unnecessarily. Can be added to documentation but not to README. If you want to change all examples from `scs` to `scg` create issue.

2023-04-10 18:35 UTC, SHtress commented on README.md
>  ```scs
Unnecessarily. Can be added to documentation but not to README. If you want to change all examples from `scs` to `scg` create issue.

2023-04-10 18:37 UTC, SHtress commented on README.md
>  ```scs
Also i try to create one PR for one feature or fix.

2023-04-10 20:50 UTC, smousy approved these changes

2023-04-11 15:33 UTC, MksmOrlov commented on README.md
> +## Repository and components
https://github.com/ostis-ai/sc-component-manager/issues/38

2023-04-11 15:34 UTC, MksmOrlov commented on README.md
>  ```scs
ok but SCn documentation MUST HAVE SCg examples

2023-04-11 15:34 UTC, MksmOrlov approved these changes

2023-04-11 15:36 UTC, merged