docs: update README about installation, build and usage
ostis-ai/sc-component-manager pull request #53
Opened 2023-07-12 12:32 UTC by MksmOrlov

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2023-07-12 17:52 UTC, SHtress reviewed
Small ideas. My version of README is attached.
[README.md](https://github.com/ostis-ai/sc-component-manager/files/12030857/README.md)

2023-07-12 17:52 UTC, SHtress commented on README.md
> +```
```suggestion
## Preparation

Install [**Subversion**](https://subversion.apache.org/) version control system.

```sh
# install subversion version control system to install specifications
sudo apt install subversion
```

Clone [**sc-machine**](https://github.com/ostis-ai/sc-machine) with branch **component_manager**.

```sh
# clone sc-machine
git clone git@github.com:ostis-ai/sc-machine.git

# checkout to the component_manager branch
git checkout component_manager
```

2023-07-12 17:52 UTC, SHtress commented on README.md
> +```
I think its better to create Preparation section than Install

2023-07-12 17:52 UTC, SHtress commented on README.md
> +``./scripts/build_sc_machine.sh -cm``
```suggestion
To build sc-machine with sc-component-manager run build script with component manager flag:

```sh
./scripts/build_sc_machine.sh -cm
```
```

2023-07-12 17:52 UTC, SHtress commented on README.md
> +To see sc-component manager debug logs go to the `sc-machine.ini`, `[sc-memory]` section and set `log_level` to `Debug`.
```suggestion
## Post Install

### Code Highlighting
To enable code highlighting:

1. Go to the `sc-machine/sc-tools/CMakeLists.txt`;
2. Set `SC_COMPONENT_MANAGER` option to the `ON`;
3. Reload CMake project.

### Debug Logs
To see sc-component manager debug logs set `log_level` to `Debug` in `[sc-memory]` section in `sc-machine.ini`
```

2023-07-13 10:10 UTC, NikitaZotov requested changes

2023-07-13 10:10 UTC, NikitaZotov commented on README.md
> +To see sc-component manager debug logs go to the `sc-machine.ini`, `[sc-memory]` section and set `log_level` to `Debug`.
```suggestion
To see sc-component-manager debug logs go to the `sc-machine.ini`, `[sc-memory]` section and set `log_level` to `Debug`.
```

2023-07-13 10:10 UTC, NikitaZotov commented on README.md
> +git checkout component_manager
```suggestion
cd sc-machine
git checkout component_manager
git submodule update --init --recursive
./scripts/install_deps_ubuntu.sh --dev
```

2023-07-13 17:45 UTC, SHtress approved these changes

2023-07-13 20:55 UTC, FallenChromium commented on README.md
> +It allows to install reusable components for intelligent systems made with using the [**OSTIS Technology**](https://github.com/ostis-ai/ostis-project).
```suggestion
It allows sc-machine to install reusable components for intelligent systems made with the [**OSTIS Technology**](https://github.com/ostis-ai/ostis-project).
```
Missing actor relative to the "allows" word.
"Made with" is kind of a sustainable saying that's roughly translated to Russian as "сделано с помощью", so "using" is redundant.

2023-07-13 21:51 UTC, FallenChromium commented on README.md
> +1. Go to the `sc-machine/sc-tools/CMakeLists.txt`;
Wouldn't it be enough to just set it on the `cmake -B build` step? I think `build_sc_machine.sh` with `-cm` flag should do that for you, and your IDE should reuse that config. If that's not the case, the user's tooling should be set up accordingly (e.g. "CMake Options" window in CLion" 🙄)

It matters mostly because you'd have to `git stash` sc-machine every time to update it, that can lead to all kind of problems with scripts that are doing `git pull` or deleting the folder altogether. This setting should be in the user-controlled environment IMO.

2023-07-13 21:52 UTC, FallenChromium commented on README.md
> +To see sc-component-manager debug logs set `log_level` to `Debug` in `[sc-memory]` section in `sc-machine.ini`
```suggestion
To see sc-component-manager debug logs, set `log_level` to `Debug` in `[sc-memory]` section of `sc-machine.ini`
```

2023-07-13 21:54 UTC, FallenChromium commented on README.md
> +- `components init` - download specifications from repositories. `kb/specifications.scs` contains example of how to describe repository.
```suggestion
- `components init` - download specifications from repositories. `kb/specifications.scs` contains an example of a repository description.
```

2023-07-13 21:55 UTC, FallenChromium commented on README.md
> +- `components search  [--author \<author\>][--class \<class\>][--explanation \<"explanation"\>]` - search component specification in knowledge base. You can search components by author, class or expl
```suggestion
- `components search  [--author \<author\>][--class \<class\>][--explanation \<"explanation"\>]` - search a component specification in the knowledge base. You can search components by author, class or explanation substring.
```

2023-07-13 21:57 UTC, FallenChromium commented on README.md
> +- `components install [--idtf \<system_idtf\>]` - install component by it's system identifier.
```suggestion
- `components install [--idtf \<system_idtf\>]` - install component by its system identifier.
```
https://www.merriam-webster.com/words-at-play/the-tangled-history-of-its-and-its

2023-07-13 21:58 UTC, FallenChromium requested changes
^

2023-07-14 12:44 UTC, FallenChromium approved these changes

2023-07-14 13:04 UTC, NikitaZotov approved these changes

2023-07-14 13:04 UTC, merged