feat: connect component manager to platform
ostis-ai/sc-component-manager pull request #67
Opened 2024-01-25 09:53 UTC by MksmOrlov

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-01-27 20:26 UTC, NikitaZotov requested changes

2024-01-27 20:26 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> +  find "${SC_COMPONENT_MANAGER_PATH}" -type d -name generated -exec rm -rf {} +
Are you sure that it works?

2024-01-27 20:26 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> +      exit 2
Fix format

2024-01-27 20:26 UTC, NikitaZotov commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DSC_DEBUG -DSC_PROFILE")
```suggestion
```

2024-01-27 20:26 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> +stage "sc-component-manager built successfully"
I think that we should write `Sc-component-manager` or `The sc-component-manager`

2024-01-27 20:26 UTC, NikitaZotov commented on scripts/run_sc_component_manager.sh
> +      ;;
This option doesn't work. And i think, that sc-component-manager has not this business

2024-01-27 20:26 UTC, NikitaZotov commented on src/CMakeLists.txt
> +target_link_libraries(sc-component-manager-lib sc-memory sc-config-utils sc-agents-common sc-builder-lib)
I propose to remove dependence from sc-agents-common in the future

2024-01-28 15:28 UTC, MksmOrlov commented on src/CMakeLists.txt
> +target_link_libraries(sc-component-manager-lib sc-memory sc-config-utils sc-agents-common sc-builder-lib)
ok, in the future

2024-01-28 15:31 UTC, MksmOrlov commented on scripts/build_sc_component_manager.sh
> +  find "${SC_COMPONENT_MANAGER_PATH}" -type d -name generated -exec rm -rf {} +
Yes

2024-01-28 18:28 UTC, NikitaZotov commented on src/CMakeLists.txt
> +target_link_libraries(sc-component-manager-lib sc-memory sc-config-utils sc-agents-common sc-builder-lib)
Create issue for this

2024-01-28 18:29 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> +done
Please, fix tabs

2024-01-29 07:41 UTC, NikitaZotov commented on src/CMakeLists.txt
> +target_link_libraries(sc-component-manager-lib sc-memory sc-config-utils sc-agents-common sc-builder-lib)
I dont' see issue

2024-01-29 07:42 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> +done
![image](https://github.com/ostis-ai/sc-component-manager/assets/56268020/9548763c-478b-4d93-8754-e2e9b1084ce3)

2024-01-29 08:25 UTC, NikitaZotov commented on scripts/run_sc_component_manager.sh
> +set -e
```suggestion
set -eo pipefail
```

2024-01-29 08:35 UTC, NikitaZotov approved these changes

2024-01-29 12:42 UTC, merged