feat: add command reduction
ostis-ai/sc-component-manager pull request #77
Opened 2024-02-07 12:15 UTC by PetrochukKsenija

You can use these reductions:
ci = components init
cs = components search
cii = components install --idtf

2024-02-07 13:37 UTC, MksmOrlov requested changes
Update changelog

2024-02-07 13:37 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    std::string const COMMAND_COMPONENTS_INSTALL_IDTF = "cii";
What if I want to add one more synonym? I'd like to have a vector of possible values to execute a command, not only one alternative.

2024-02-07 15:10 UTC, MakarenkoAI approved these changes

2024-02-07 15:10 UTC, MakarenkoAI commented on README.md
> +- `components install [--idtf \<system_idtf\>]` or `cii \<system_idtf\>` - install component by its system identifier.
```suggestion
- `components init` - download specifications from repositories. `kb/specifications.scs` contains an example of a repository specification.
  - _Abbreviation_: You can use `ci` instead of `components init`.
- `components search` with `[--author \<author\>][--class \<class\>][--explanation \<"explanation"\>]` - search a component specification in the knowledge base. You can search components by author, class or explanation substring.
  - _Abbreviation_: You can use `cs` instead of `components search`.
- `components install` with ` [--idtf \<system_idtf\>]` - install component by its system identifier.
  - _Abbreviation_: You can use `cii` instead of `components install`.
```
Мне нравится и как у тебя. Но возможно читать удобнее будет

2024-02-09 13:45 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
>      size_t const COMMAND_KEYWORDS_SIZE = 2;
All this constants should be in static class fields

2024-02-11 14:28 UTC, MakarenkoAI commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +          break;
В этом случае мы выйдем из второго for и будем продолжать искать возможную замену. Не страшно, но чем больше список, тем больше итераций. Наверное, можно добавить такое или закончить поиск иначе
```suggestion
          indexCommand = COMMAND_LIST.size();
          break;
```
Еще Максим просил проверить работают ли сокращения. Проверила, все круто

2024-02-12 07:05 UTC, MksmOrlov requested changes

2024-02-12 07:05 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    static std::vector<std::vector <std::string>> const COMMAND_LIST = {COMMAND_COMPONENTS_INIT, COMMAND_COMPONENTS_SEARCH, COMMAND_COMPONENTS_INSTALL};
All this constants should be in static **_class fields_**

2024-02-12 07:05 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    static std::vector<std::vector <std::string>> const COMMAND_LIST = {COMMAND_COMPONENTS_INIT, COMMAND_COMPONENTS_SEARCH, COMMAND_COMPONENTS_INSTALL};
В текущем варианте у тебя объекты создаются каждый раз, когда вызываешь метод _Parse_. А надо, чтобы они один раз создались при создании объекта класса _ScComponentManagerParser_ и могли использоваться где угодно ещё без пересоздания

2024-02-14 08:34 UTC, MksmOrlov requested changes
Да, ты права, так лучше

2024-02-14 08:34 UTC, MksmOrlov commented on src/manager/commands/constants/command_constants.hpp
> +#include <regex>
why do you need regex? Remove unused

2024-02-14 08:34 UTC, MksmOrlov commented on src/manager/commands/constants/command_constants.hpp
> +  static std::vector<std::string> const COMMAND_COMPONENTS_INIT;
add also std::string const COMPONENTS_COMMAND_PREFIX = "components";

2024-02-14 09:32 UTC, MksmOrlov approved these changes

2024-02-14 10:58 UTC, merged