[fix] flag --explanation with empty value
ostis-ai/sc-component-manager pull request #79
Opened 2024-02-13 11:12 UTC by MakarenkoAI

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-02-14 09:39 UTC, MksmOrlov approved these changes

2024-02-16 10:01 UTC, NikitaZotov requested changes

2024-02-16 10:01 UTC, NikitaZotov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +          currentCommandToken = currentCommandToken.substr(1, currentCommandToken.size() - 2);
Please, add tests

2024-02-16 10:01 UTC, NikitaZotov commented on src/manager/commands/command_search/sc_component_manager_command_search.cpp
> +  if (commandParameters.find(EXPLANATION) != commandParameters.cend() &&
Please, add tests

2024-02-17 16:16 UTC, NikitaZotov approved these changes

2024-02-17 16:16 UTC, NikitaZotov commented
Please, update changelog

2024-02-18 11:42 UTC, merged