[fix] Flag --idtf
ostis-ai/sc-component-manager pull request #80
Opened 2024-02-13 16:11 UTC by MakarenkoAI

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-02-14 09:20 UTC, MksmOrlov requested changes

2024-02-14 09:20 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +  inline static std::string const PARAMETER_IDTF = "idtf";
why do you need inline? I'd like to remove it

2024-02-14 09:20 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +  inline static std::string const PARAMETER_IDTF = "idtf";
Move it to the command constants class

2024-02-14 11:09 UTC, MakarenkoAI commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +  inline static std::string const PARAMETER_IDTF = "idtf";
так в интернете написали и без inline не работает

2024-02-15 10:15 UTC, MksmOrlov requested changes
fix warning in test
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/96b52a84-7c02-485e-9461-0351745d10e3)

2024-02-15 10:15 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +          indexCommand = int(CommandConstants::COMMAND_LIST.size());
both are size_t, no need to do int()

2024-02-15 15:45 UTC, MksmOrlov approved these changes

2024-02-16 06:03 UTC, MakarenkoAI commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    else
Возможно тут добавить нужно проверку на то, что команда = install, чтобы в будущем не ломало

2024-02-16 09:43 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    else
конечно нужно

2024-02-16 10:00 UTC, NikitaZotov requested changes

2024-02-16 10:00 UTC, NikitaZotov commented on tests/units/test_command_parser.cpp
> +  EXPECT_EQ(size_t(0), commandValues.size());
```suggestion
  EXPECT_EQ(0u, commandValues.size());
```

2024-02-16 10:00 UTC, NikitaZotov commented on tests/units/test_command_parser.cpp
> +  EXPECT_EQ(size_t(1), commandValues.size());
```suggestion
  EXPECT_EQ(1u, commandValues.size());
```

2024-02-16 10:00 UTC, NikitaZotov commented on thirdparty/CMakeLists.txt
> +	include(gtest.cmake)
```suggestion
    include(gtest.cmake)
```

2024-02-16 18:17 UTC, NikitaZotov approved these changes

2024-02-17 15:34 UTC, merged