[install] Fix the parse of commands
ostis-ai/sc-component-manager pull request #82
Opened 2024-02-19 11:01 UTC by MakarenkoAI

2024-02-20 11:22 UTC, MksmOrlov requested changes
как насчёт того, чтобы в методе парсинга команды сначала сделать этап предобработки, а потом парсить так, как парсилось раньше.
1. Заменяем сокращение на полное представление. Для этого создай мапку {сокращение : полная команда} вместо векторов, как сделано сейчас
2. Проверяем, если команда установки и нету флага идтф, добавляем его
3. Парсим полную форму команды, как делалось раньше
Сейчас куча лишних обходов сделано

2024-02-21 18:11 UTC, MakarenkoAI commented
> как насчёт того, чтобы в методе парсинга команды сначала сделать этап предобработки, а потом парсить так, как парсилось раньше.
> 
>     1. Заменяем сокращение на полное представление. Для этого создай мапку {сокращение : полная команда} вместо векторов, как сделано сейчас
> 
>     2. Проверяем, если команда установки и нету флага идтф, добавляем его
> 
>     3. Парсим полную форму команды, как делалось раньше
>        Сейчас куча лишних обходов сделано

Логика получилась немного другой. 
1. Посдставляем все сокращения, если они есть
2.

2024-02-21 18:52 UTC, MksmOrlov requested changes

2024-02-21 18:52 UTC, MksmOrlov commented on src/manager/commands/constants/command_constants.cpp
> +    {"comp inst", CommandConstants::COMMAND_COMPONENTS_INSTALL[0]}};
you always use only [0] element. So, remove vector of command and use just full name of the command. Your map is a replace for vector

2024-02-21 18:52 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +  static std::string CheckIfAbbreviationCommand(std::string const & command)
Methods with a name starts with "Check" are used to return bool value. Rename it to "GetFullCommand or something"

2024-02-21 18:53 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +        break;
сомнительно, но окей

2024-02-21 19:44 UTC, MksmOrlov approved these changes

2024-02-21 19:44 UTC, MksmOrlov commented on src/manager/command_parser/sc_component_manager_command_parser.hpp
> +    for (size_t index = 0u; index < command.size() - 1; index++)
```suggestion
    for (size_t index = 0; index < command.size() - 1; index++)
```

2024-02-23 16:53 UTC, merged