[docs] Add docs of cmake configuraion
ostis-ai/sc-component-manager pull request #84
Opened 2024-02-21 13:53 UTC by MakarenkoAI

2024-02-21 19:14 UTC, MksmOrlov requested changes
In test scenario
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/b0fb524e-ef46-4214-b7a2-2620a1cc0d3e)

2024-02-21 20:01 UTC, MksmOrlov approved these changes

2024-02-22 08:08 UTC, NikitaZotov requested changes

2024-02-22 08:08 UTC, NikitaZotov commented on docs/dev/cmake_configuration.md
> +    -DSC_BIN_PATH="~/ostis-metasystem/bin"
```suggestion
    -DSC_BIN_PATH="<path-to-binary-folder>"
```

2024-02-22 08:08 UTC, NikitaZotov commented on docs/dev/cmake_configuration.md
> +   -c ostis-metasystem.ini
```suggestion
   -c  <path-to-config-ini-file>
```

2024-02-22 08:08 UTC, NikitaZotov commented on docs/dev/cmake_configuration.md
Update changelog

2024-02-23 11:03 UTC, NikitaZotov approved these changes

2024-02-23 11:29 UTC, merged