Docs/agents
ostis-ai/sc-component-manager pull request #85
Opened 2024-02-22 09:28 UTC by MakarenkoAI

2024-02-22 10:00 UTC, MksmOrlov commented on docs/agents.tex
> +	\scnfileitem{Отыскать все спецификаци многократно используемых компонентов в базе знаний.}
```suggestion
	\scnfileitem{Отыскать все спецификаци спецификаций многократно используемых компонентов в базе знаний.}
```

2024-02-22 10:01 UTC, MksmOrlov commented on docs/agents.tex
> +	\scntext{примечание}{В результате выполнения агентом поискового действия на устройстве появятся scs-файлы со спецификациями, скаченными по сети.}
И ТРАНСЛИРОВАННЫЕ В ПАМЯТЬ

2024-02-22 10:08 UTC, MksmOrlov commented on docs/images/install_in.png
rrel_identifier

2024-02-22 10:11 UTC, MksmOrlov commented on docs/agents.tex
> +	\scntext{примечание}{В результате выполнения агентом поискового действия на устройстве появятся scs-файлы со спецификациями, скаченными по сети.}
агент загрузки спецификаций имеет ответ агента поиска спецификаций. Неправильно

2024-02-22 10:12 UTC, MksmOrlov commented on docs/agents.tex
> +\scnheader{Агент поиска компонента}
```suggestion
\scnheader{Агент поиска компонентов}
```

2024-02-22 10:21 UTC, MakarenkoAI commented on docs/agents.tex
> +	\scntext{примечание}{В результате выполнения агентом поискового действия на устройстве появятся scs-файлы со спецификациями, скаченными по сети.}
Okay okay

2024-02-22 17:53 UTC, MksmOrlov requested changes
Сделай пожалуйста ещё спецификацию агента получения спецификации компонента по компоненту

2024-02-22 17:53 UTC, MksmOrlov commented on docs/agents.tex
> +\scnrelfrom{ответ агента}{ответ агента поиска спецификаций}
поиск спецификаций или компонентов?

2024-02-22 18:40 UTC, MakarenkoAI commented
> Сделай пожалуйста ещё спецификацию агента получения спецификации компонента по компоненту

What do you mean?

2024-02-22 18:42 UTC, MakarenkoAI commented on docs/agents.tex
> +\scnrelfrom{ответ агента}{ответ агента поиска спецификаций}
I don't know how to nane this, semanticheskaya okrestnost

2024-02-23 06:47 UTC, MksmOrlov requested changes

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +\end{scnrelfromset}
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/8729d374-7ace-443c-aea2-fda73d5bb3ed)
это уже написано выше, не нужно дублировать

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +\end{scnrelfromset}
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/b7efba73-8727-4e37-b78f-f98e33893f06)
Здесь не надо описывать декомпозицию решателя, уже есть выше. Для абстрактного агента поиска и установки компонентов сделай пятёрочку => реализация:* в "Агент установки компонентов" и в "Агент поиска компонентов". Для агента установки спецификаций (init) сделай просто включение в решатель задач м.к.

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +	\scnitem{Агент поиска компонента}
```suggestion
	\scnitem{Агент поиска компонентов}
```

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +	\scnitem{Агент загрузки компонента}
```suggestion
	\scnitem{Агент установки компонентов}
```

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +\scnrelfrom{ответ агента}{ответ агента поиска спецификаций}
```suggestion
\scnrelfrom{ответ агента}{ответ агента установки спецификаций многократно используемых компонентов}
```

2024-02-23 06:47 UTC, MksmOrlov commented on docs/agents.tex
> +\begin{scnrelfromvector}{аргументы агента}
```suggestion
\begin{scnrelfromset}{возможные аргументы агента}
```
А то подумают, что надо каждый из аргументов задавать и в таком порядке

2024-02-23 06:57 UTC, MakarenkoAI commented on docs/agents.tex
> +\begin{scnrelfromvector}{аргументы агента}
Youre definitely right

2024-02-23 10:46 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/aab52afa-0f4b-4ca5-bfab-fad2b4fd95fb)

2024-02-23 11:05 UTC, MksmOrlov approved these changes

2024-02-23 11:20 UTC, merged