Agents
ostis-ai/sc-component-manager pull request #87
Opened 2024-02-28 22:07 UTC by MakarenkoAI

2024-03-12 10:14 UTC, MksmOrlov requested changes
Make separate modules for every agent like in projects. search module, init module, install module. Module must have "agent" directory and directory with agent logic that is used in commands too. And utils if needed. Common keynodes and utils and constants for all the agents should be placed in common module

Rename “commands” directory to "agents" and "command_x" to "agent_x". We need to remove "command" word where the common logic takes place.

2024-03-14 16:53 UTC, MksmOrlov requested changes

2024-03-14 16:53 UTC, MksmOrlov commented on src/manager/interface_manager/CMakeLists.txt
> +add_library(interface SHARED ${SOURCES})
interface sounds loud. Rename to console_interface

2024-03-14 16:53 UTC, MksmOrlov commented on src/manager/interface_manager/sc_component_manager_command_handler.hpp
> +        actionAddrClass = keynodes::ScComponentManagerKeynodes::action_components_install;
get it by map `at` method

2024-03-14 16:53 UTC, MksmOrlov commented on src/manager/interface_manager/sc_component_manager_command_handler.hpp
> +  }
delete unused method

2024-03-14 16:53 UTC, MksmOrlov commented on tests/units/agent_tests.cpp
> +  if (componentsIterator->Next())
```suggestion
  EXPECT_TRUE (componentsIterator->Next())
```
and delete else construction. Same in all tests

2024-03-14 16:57 UTC, MakarenkoAI commented on src/manager/agents/common-module/utils/common_utils.cpp
> +      for (const std::string & valueOfParameter : parameter.second)
нет, не слышали

2024-03-14 17:11 UTC, MakarenkoAI commented on src/manager/agents/common-module/utils/common_utils.cpp
> +          }
But this quest from user will be saved in knowledge base

2024-03-14 17:16 UTC, MakarenkoAI commented on src/manager/agents/install-module/agents/sc_component_manager_agent_install.cpp
> +  std::map<ScAddr, std::string, ScAddrLessFunc> config_path;
no

2024-03-15 09:26 UTC, MksmOrlov commented on src/manager/agents/common-module/utils/common_utils.cpp
> +      for (const std::string & valueOfParameter : parameter.second)
а надо послушать :)

2024-03-15 09:28 UTC, MksmOrlov commented on src/manager/agents/install-module/agents/sc_component_manager_agent_install.cpp
> +  std::map<ScAddr, std::string, ScAddrLessFunc> config_path;
cofig_path is understandable for me as path (string) to config file. But there is a config with paths for components. Different things, you know?

2024-03-18 09:50 UTC, MksmOrlov requested changes

2024-03-18 09:50 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +          continue;
SC_LOG_WARNING неизвестный параметр value

2024-03-18 09:50 UTC, MksmOrlov commented on src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.cpp
> +  std::string const config_path = "/home/anna/projects/ostis-metasystem/sc-models/knowledge-base";
```suggestion
  std::string const config_path = ScMemory::ms_configPath;
```
Then create a config object and from this object get the kb field from the sc-component-manager section. There seems to be such a logic in Main

2024-03-21 10:19 UTC, MksmOrlov requested changes

2024-03-21 10:19 UTC, MksmOrlov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +  for (const auto & parameter : commandParameters)
```suggestion
  for (auto const & parameter : commandParameters)
```

2024-03-21 11:32 UTC, MksmOrlov commented on kb/actions.scs
> +<- sc_node_clas;
```suggestion
<- sc_node_class;
```

2024-03-21 11:45 UTC, MksmOrlov requested changes

2024-03-21 11:45 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +      *context, actionAddr, keynodes::ScComponentManagerKeynodes::rrel_identifier);
I think, we don't need to find by role rrel_identifier. We just pass component nodes to install, there is no identifier. Remove it and update documentation please

2024-03-21 16:36 UTC, MksmOrlov requested changes
Make try catch constructions in agent
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/0fb95909-f215-45e1-9f9a-3f7208e258b0)
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/90d8d667-af70-48be-a57d-dbd39e238d1e)

2024-03-21 16:58 UTC, MksmOrlov requested changes
update changelog

2024-03-24 07:50 UTC, MksmOrlov requested changes
1. fix installation all the components if something wrong is passed
2. update action constructions in scn documentation
3. update changelog

2024-03-25 18:17 UTC, MksmOrlov requested changes

2024-03-25 18:17 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +    componentsToInstallIdentifiers.push_back(context->HelperGetSystemIdtf(identifierNode));
это очень странный момент, сначала получаем системник по узлу, а потом передаем это в метод, который получает узел по системнику. Сделай работу только с узлами здесь и там (GetAvailableComponents)

2024-03-25 18:17 UTC, MksmOrlov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +    if(executionResult) {
```suggestion
    if (executionResult) {
```

2024-03-26 06:24 UTC, MakarenkoAI commented on docs/images/cs_param.png
No, singular form

2024-03-26 06:55 UTC, MakarenkoAI commented on src/main.cpp
> +  ;
why it works with that...

2024-03-26 07:00 UTC, MakarenkoAI commented on src/manager/agents/common-module/utils/sc_component_utils.cpp
> +      result |= loader.loadScsFile(*context, filePath);
removed

2024-03-26 07:22 UTC, MksmOrlov commented on src/main.cpp
> +  ;
It is correct for c++ syntax. Empty statement do nothing

2024-03-26 07:57 UTC, MksmOrlov requested changes

2024-03-26 07:57 UTC, MksmOrlov commented on docs/images/cinst.png
concept_reusable_component это же множество компонентов, а не компонент, он не может быть элементом множества скачиваемых компонентов. Замени здесь просто на component_3, а если хочешь показать, что можно скачать все компоненты какого-то класса, то сделай отдельный рисунок, где будет этот класс под первой ролью у action_node

2024-03-26 07:57 UTC, MksmOrlov commented on docs/agents.tex
> +		\scntext{примечание}{В этом случае агент не будет скачивать компоненты.}
вместо всего этого оставь "множество компонентов" и скажи, что скачиваются все компоненты из этого множества. Этого будет достаточно. И переименуй здесь "возможные аргументы агента" в "аргументы агента"

2024-03-26 08:34 UTC, MksmOrlov commented on docs/images/cs_param.png
why? I think, we may pass many authors. И ниже у тебя в аргументах "авторЫ"

2024-03-26 08:45 UTC, MakarenkoAI commented on docs/images/cinst.png
а если захочу несколько классов?

2024-03-26 08:45 UTC, MakarenkoAI commented on docs/images/cs_param.png
задача* не задачи*, решение*. я за ед.число

2024-03-26 08:50 UTC, MksmOrlov commented on docs/images/cs_param.png
если задач много, то тоже задача*?

2024-03-26 08:50 UTC, MksmOrlov commented on docs/images/cinst.png
сейчас так реализовано?

2024-03-26 08:54 UTC, MakarenkoAI commented on docs/images/cinst.png
да именно так

2024-03-26 08:54 UTC, MakarenkoAI commented on docs/images/cinst.png
думаю в теории и только класс подойдет сразу под rrel_1, и любое другое множество с элементами

2024-03-26 08:55 UTC, MakarenkoAI commented on docs/images/cs_param.png
да, задачи* и задача* это одно и то же отношение

2024-03-26 11:05 UTC, MksmOrlov approved these changes

2024-03-29 15:12 UTC, NikitaZotov requested changes

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/console-interface/command_parser/sc_component_manager_command_parser.hpp
> +#include "../../agents/common-module/constants/command_constants.hpp"
```suggestion
#include "common-module/constants/command_constants.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/common-module/utils/sc_component_utils.cpp
> +#include "../../agents/common-module/url_parser/repository_url_parser.hpp"
```suggestion
#include "common-module/module/keynodes/ScComponentManagerKeynodes.hpp"
#include "common-module/constants/command_constants.hpp"
#include "common-module/url_parser/repository_url_parser.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +#include "../../common-module/downloader/downloader.hpp"
```suggestion
#include "common-module/downloader/downloader.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +#include "../../agents/common-module/module/utils/common_utils.hpp"
```suggestion
#include "common-module/module/utils/common_utils.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +#include "../../agents/common-module/module/utils/common_utils.hpp"
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.cpp
> +#include <sc-agents-common/utils/AgentUtils.hpp>
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/init-module/utils/sc_component_manager_command_init.cpp
> +#include "../../common-module/downloader/downloader.hpp"
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/init-module/module/agents/sc_component_manager_agent_init.cpp
> +#include <sc-agents-common/utils/AgentUtils.hpp>
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/common-module/utils/sc_component_utils.cpp
>  #include <sc-agents-common/utils/CommonUtils.hpp>
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/agents/common-module/module/utils/common_utils.cpp
> +#include "common_utils.hpp"
Sort includes, please, according to our Codestyle

2024-03-29 15:12 UTC, NikitaZotov commented on tests/tests.cmake
> +    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${GLIB2_LIBRARIES}}
```suggestion
    INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${GLIB2_LIBRARIES} ${CONSOLE_INTERFACE_SRC}}
```

2024-03-29 15:12 UTC, NikitaZotov commented on src/manager/console-interface/CMakeLists.txt
> +file(GLOB_RECURSE SOURCES "*.cpp" "*.hpp")
```suggestion
set(CONSOLE_INTERFACE_SRC ${CMAKE_CURRENT_LIST_DIR})
file(GLOB_RECURSE SOURCES "*.cpp" "*.hpp")
```

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/sc_component_manager_test.hpp
> +#include "../../src/manager/console-interface/command_parser/sc_component_manager_command_parser.hpp"
```suggestion
#include "command_parser/sc_component_manager_command_parser.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/test_url_parser.cpp
> +#include "../../src/manager/agents/common-module/url_parser/repository_url_parser.hpp"
```suggestion
#include "common-module/url_parser/repository_url_parser.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/agent_tests.cpp
> +#include "../../src/manager/agents/install-module/module/agents/sc_component_manager_agent_install.hpp"
```suggestion
#include "common-module/module/keynodes/ScComponentManagerKeynodes.hpp"

#include "init-module/module/agents/sc_component_manager_agent_init.hpp"
#include "search-module/module/agents/sc_component_manager_agent_search.hpp"
#include "install-module/module/agents/sc_component_manager_agent_install.hpp"
```

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/agent_tests.cpp
> +#include <gtest/gtest.h>
Sort includes

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/agent_tests.cpp
> +void initialize()
```suggestion
void Initialize()
```

2024-03-29 15:12 UTC, NikitaZotov commented on tests/units/agent_tests.cpp
> +  std::vector<std::string> namesOfComponents = {"part_platform", "part_ui"};
Check var names

2024-03-29 17:04 UTC, MakarenkoAI commented on src/manager/agents/install-module/utils/sc_component_manager_command_install.cpp
> +  ScAddrVector componentsToInstall =
its not constant

2024-04-09 09:33 UTC, NikitaZotov requested changes

2024-04-09 09:33 UTC, NikitaZotov commented on src/manager/agents/common-module/constants/command_constants.cpp
> +std::string const PathKeysOfConfigPath::UI_PATH = "interface_components_path";
New line

2024-04-09 09:33 UTC, NikitaZotov commented on src/main.cpp
> +  common_utils::CommonUtils::InitParametersMap();
Not fixed

2024-04-13 12:50 UTC, merged