[scripts] Use build_cxx_project.sh for build_sc_component_manager.sh
ostis-ai/sc-component-manager pull request #88
Opened 2024-03-05 15:52 UTC by NikitaZotov

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-03-06 08:46 UTC, MksmOrlov requested changes

2024-03-06 08:46 UTC, MksmOrlov commented on CMakeLists.txt
> +    message(SEND_ERROR "SC-component-manager isn't supported on Windows OS.")
```suggestion
    message(SEND_ERROR "sc-component-manager isn't supported on Windows OS.")
```

2024-03-06 08:46 UTC, MksmOrlov commented on scripts/build_sc_component_manager.sh
> +stage "SC-component-manager built successfully"
```suggestion
stage "sc-component-manager built successfully"
```

2024-03-10 10:59 UTC, MakarenkoAI commented on scripts/build_sc_component_manager.sh
> +stage "SC-component-manager built successfully"
_is_ built, and why "sc"?

2024-03-10 12:02 UTC, MakarenkoAI requested changes
![image](https://github.com/ostis-ai/sc-component-manager/assets/90891293/818b155e-1c43-4bb5-bf78-082e0c2b4b30)
sc-machine and manager : feat/improve_build
reload cmake, build
then reload cmake in manager

2024-03-10 12:15 UTC, MakarenkoAI requested changes

2024-03-10 12:15 UTC, MakarenkoAI commented on CMakeLists.txt
> +if(${SC_BUILD_TESTS})
why test.cmake included twice, here and on the 56 line

2024-03-10 12:15 UTC, MakarenkoAI commented on CMakeLists.txt
> +if(${SC_BUILD_TESTS})
why test.cmake included twice, here and on the 56 line

2024-03-11 09:11 UTC, NikitaZotov commented on CMakeLists.txt
> +if(${SC_BUILD_TESTS})
Firstly, we include cmake for configure any tests. Secondly, we include cmake for some tests. There are different cmakes

2024-03-12 07:24 UTC, MksmOrlov requested changes

2024-03-12 07:24 UTC, MksmOrlov commented on README.md
> +This repository is a storage of the Component manager of the [OSTIS Project](https://github.com/ostis-ai/ostis-project).
![image](https://github.com/ostis-ai/sc-component-manager/assets/36566977/b702b7cc-fe0a-4ae2-80a6-97bfdf06a456)

2024-03-12 07:24 UTC, MksmOrlov commented on README.md
> +**Repositories** have links for source (GitHub, Google Drive etc.) with specification file, **components** have links to source with specification of component.
```suggestion
**Repositories** have links for source on GitHub with specification file, **components** have links to source with specification of component.
```

2024-03-12 07:27 UTC, MksmOrlov requested changes
Update codegen path in manager cmake to find only in keynodes directory

2024-03-13 19:09 UTC, MakarenkoAI approved these changes

2024-03-16 09:37 UTC, MksmOrlov requested changes

2024-03-16 09:37 UTC, MksmOrlov commented on README.md
> +This repository is a storage of the Component manager of the [OSTIS Project](https://github.com/ostis-ai).
I think, repository is a storage itself and there is no need to duplicate it info.

2024-03-16 09:46 UTC, MksmOrlov approved these changes

2024-03-16 09:47 UTC, merged