[kb] Add new components specification
ostis-ai/sc-component-manager pull request #89
Opened 2024-03-06 10:50 UTC by PetrochukKsenija

* [ ] Update changelog if needed
* [ ] Update SCn documentation if needed

2024-03-10 14:06 UTC, MakarenkoAI commented on kb/specifications.scs
![image](https://github.com/ostis-ai/sc-component-manager/assets/90891293/c61d2e97-b40b-4f86-b885-5b6bfdd3b43b)
это точно всё kb_components не ui|ps?

2024-03-10 14:09 UTC, MakarenkoAI commented on kb/specifications.scs
и еще вопрос, почему где-то logic rule, где-то formula

2024-03-10 15:10 UTC, MakarenkoAI approved these changes

2024-03-11 11:13 UTC, MksmOrlov requested changes
Ветку на гитхабе в менеджере переименуй пожалуйста в "demo"
part_figure надо переименовать в sd_triangles, там ведь только треугольники
В правилах "part_lr_about..." надо убрать приставку part_, это ведь не раздел базы знаний
Правила надо на scs переписать, иначе они в рантайме не протранслируются в базу

2024-04-17 10:23 UTC, merged